//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAAANJ49gnxnC+7tn0Vmxyjgp+0zWlr38ttQtMxYA1+D7r8")]
        public string IsHiddenAppMode {
            get {
                return ((string)(this["IsHiddenAppMode"]));
            }
            set {
                this["IsHiddenAppMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAAAKB7cg6twdeJKP/lZhxnP2FyLZsuwtTcX89WGE+OB1hefevn9ydcgMf+yF0Tte3OcQ==")]
        public string EmailAddressFrom {
            get {
                return ((string)(this["EmailAddressFrom"]));
            }
            set {
                this["EmailAddressFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAAAEz49LVCHMWwfhHidRqz0OE6vd58NWUcAU+y3tDiu+UG")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAAAB2nPaJI0z442fHjKuLeW3nNOS75uorALFeenYxiU9yqdyNFrJPYdPmz1FJ646H4zQ==")]
        public string EmailAddressTo {
            get {
                return ((string)(this["EmailAddressTo"]));
            }
            set {
                this["EmailAddressTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EAAAAMvKbGBWJkTdwUNE7jgwDVeLAHH5rMtM+Lcgy+nl5nzr")]
        public string FileSize {
            get {
                return ((string)(this["FileSize"]));
            }
            set {
                this["FileSize"] = value;
            }
        }
    }
}
